In [38]:
import torch
from torch import nn

In [39]:
x=torch.randn(4,5)
print(x)

tensor([[ 0.8332,  1.2289, -2.5414,  1.2525, -0.9389],
        [ 0.3214,  0.3583, -0.6925,  1.7809,  0.1849],
        [-0.1985,  0.5603,  0.3599,  1.5247, -1.7335],
        [-1.8723,  0.4543,  0.1932,  0.4416,  0.7460]])


In [40]:
m=nn.BatchNorm1d(5)

In [41]:
m.weight,m.bias

(Parameter containing:
 tensor([1., 1., 1., 1., 1.], requires_grad=True),
 Parameter containing:
 tensor([0., 0., 0., 0., 0.], requires_grad=True))

In [42]:
output=m(x)

In [43]:
output

tensor([[ 1.0451,  1.6937, -1.6243,  0.0051, -0.5221],
        [ 0.5415, -0.8553, -0.0193,  1.0563,  0.6433],
        [ 0.0301, -0.2640,  0.8942,  0.5466, -1.3463],
        [-1.6167, -0.5744,  0.7495, -1.6079,  1.2252]],
       grad_fn=<NativeBatchNormBackward0>)

In [44]:
output.mean(dim=0)

tensor([ 2.9802e-08,  0.0000e+00, -5.9605e-08, -5.9605e-08,  0.0000e+00],
       grad_fn=<MeanBackward1>)

In [45]:
output.std(dim=0,unbiased=False) 

tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000], grad_fn=<StdBackward0>)

In [46]:
mean=x.mean(dim=0)

In [47]:
mean

tensor([-0.2290,  0.6504, -0.6702,  1.2499, -0.4354])

In [50]:
std=torch.sqrt(1e-5+torch.var(x,dim=0,unbiased=False))

In [51]:
std

tensor([1.0164, 0.3416, 1.1520, 0.5027, 0.9642])

In [52]:
(x-mean)/std

tensor([[ 1.0451,  1.6937, -1.6243,  0.0051, -0.5221],
        [ 0.5415, -0.8553, -0.0193,  1.0563,  0.6433],
        [ 0.0301, -0.2640,  0.8942,  0.5466, -1.3463],
        [-1.6167, -0.5744,  0.7495, -1.6079,  1.2252]])

In [54]:
m(x)

tensor([[ 1.0451,  1.6937, -1.6243,  0.0051, -0.5221],
        [ 0.5415, -0.8553, -0.0193,  1.0563,  0.6433],
        [ 0.0301, -0.2640,  0.8942,  0.5466, -1.3463],
        [-1.6167, -0.5744,  0.7495, -1.6079,  1.2252]],
       grad_fn=<NativeBatchNormBackward0>)

In [55]:
x2=torch.randn(2,3,2,2)

In [56]:
x2

tensor([[[[ 4.1565e-02,  1.1205e+00],
          [-1.0709e+00, -1.8868e-01]],

         [[-1.8310e-03,  1.0647e+00],
          [-7.7611e-03, -3.8762e-01]],

         [[ 3.0861e-01,  5.1556e-01],
          [ 1.8704e-01, -6.3858e-04]]],


        [[[ 6.9480e-01, -1.0051e+00],
          [-4.5387e-01, -2.4652e-01]],

         [[ 3.5592e-01, -1.6001e+00],
          [ 3.8048e-01, -1.3849e+00]],

         [[ 1.3058e+00, -7.6932e-02],
          [ 3.0813e-01, -1.6407e+00]]]])

In [57]:
m2=nn.BatchNorm2d(3)

In [58]:
m2(x2)

tensor([[[[ 0.2532,  1.7704],
          [-1.3111, -0.0705]],

         [[ 0.2315,  1.4927],
          [ 0.2245, -0.2246]],

         [[ 0.2523,  0.5197],
          [ 0.0952, -0.1473]]],


        [[[ 1.1718, -1.2185],
          [-0.4434, -0.1519]],

         [[ 0.6546, -1.6584],
          [ 0.6836, -1.4040]],

         [[ 1.5409, -0.2459],
          [ 0.2517, -2.2665]]]], grad_fn=<NativeBatchNormBackward0>)

In [59]:
import numpy as np
t=[ 0.2532,  1.7704,-1.3111, -0.0705,1.1718, -1.2185,-0.4434, -0.1519]
np.std(t)

0.9999946574857287

In [60]:
np.mean(t)

1.3877787807814457e-17